version: '3.8'

services:
  web:
    build:
      context: ../../ # 从项目根目录构建
      dockerfile: apps/web/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      # Orama Cloud 配置
      - NEXT_PUBLIC_ORAMA_API_KEY=${NEXT_PUBLIC_ORAMA_API_KEY:-UPc31JnTgKtFPL3bUzL18XfZ8zyiiz0G}
      - NEXT_PUBLIC_ORAMA_ENDPOINT=${NEXT_PUBLIC_ORAMA_ENDPOINT:-https://cloud.orama.run/v1/indexes/nestjs-docs-leoku-dev-j21flz}
      # 功能开关
      - NEXT_PUBLIC_ENABLE_PAID_CONTENT_MODE=${NEXT_PUBLIC_ENABLE_PAID_CONTENT_MODE:-false}
      # API 配置 - 生产环境需要调整这些地址
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE:-http://localhost:8007}
      - NEXT_PUBLIC_API_PROXY_SOURCE=${NEXT_PUBLIC_API_PROXY_SOURCE:-/api}
      - NEXT_PUBLIC_API_PROXY_DESTINATION=${NEXT_PUBLIC_API_PROXY_DESTINATION:-http://host.docker.internal:8007/api}
      # 项目标识
      - NEXT_PUBLIC_PROJECT_FLAG=${NEXT_PUBLIC_PROJECT_FLAG:-crowd-test}
    restart: unless-stopped
    # 如果后端也在 Docker 中运行，可以添加网络配置
    # networks:
    #   - app-network
# 如果需要与其他服务（如数据库、后端API）连接，可以取消注释以下配置
# networks:
#   app-network:
#     driver: bridge
