/**
 * 业务状态码定义
 *
 * 设计原则：
 * - 使用 5 位数字状态码，便于分类管理
 * - 第一位表示大类：1-成功，2-客户端错误，3-服务端错误，4-业务错误
 * - 后四位表示具体错误类型
 * - 保持状态码的语义化和易读性
 */

// 成功状态码 (10000-19999)
const SUCCESS_CODES = {
  // 通用成功
  SUCCESS: 10000,
  CREATED: 10001,
  UPDATED: 10002,
  DELETED: 10003,

  // 认证相关成功
  LOGIN_SUCCESS: 10100,
  LOGOUT_SUCCESS: 10101,
  TOKEN_REFRESHED: 10102,
  PASSWORD_RESET_SUCCESS: 10103,

  // 用户相关成功
  USER_CREATED: 10200,
  USER_UPDATED: 10201,
  USER_ACTIVATED: 10202,
  USER_DEACTIVATED: 10203,

  // 组织相关成功
  ORGANIZATION_CREATED: 10300,
  ORGANIZATION_UPDATED: 10301,
  MEMBER_ADDED: 10302,
  MEMBER_REMOVED: 10303,

  // 漏洞报告相关成功
  BUG_REPORT_CREATED: 10400,
  BUG_REPORT_UPDATED: 10401,
  BUG_REPORT_SUBMITTED: 10402,
  BUG_REPORT_APPROVED: 10403,
  BUG_REPORT_REJECTED: 10404,
  BUG_REPORT_RESOLVED: 10405,
  BUG_REPORT_CLOSED: 10406,
  BUG_REPORT_STATUS_UPDATED: 10407,
} as const

// 客户端错误状态码 (20000-29999)
const CLIENT_ERROR_CODES = {
  // 通用客户端错误
  BAD_REQUEST: 20000,
  VALIDATION_ERROR: 20001,
  MISSING_PARAMETER: 20002,
  INVALID_PARAMETER: 20003,

  // 认证相关错误
  UNAUTHORIZED: 20100,
  INVALID_TOKEN: 20101,
  TOKEN_EXPIRED: 20102,
  INVALID_CREDENTIALS: 20103,
  ACCOUNT_DISABLED: 20104,

  // 权限相关错误
  FORBIDDEN: 20200,
  INSUFFICIENT_PERMISSIONS: 20201,
  RESOURCE_ACCESS_DENIED: 20202,

  // 资源相关错误
  NOT_FOUND: 20300,
  USER_NOT_FOUND: 20301,
  ORGANIZATION_NOT_FOUND: 20302,
  DEPARTMENT_NOT_FOUND: 20303,
  RESOURCE_NOT_FOUND: 20304,

  // 冲突错误
  CONFLICT: 20400,
  EMAIL_ALREADY_EXISTS: 20401,
  ORGANIZATION_NAME_EXISTS: 20402,
  ORGANIZATION_CODE_EXISTS: 20403,
  DEPARTMENT_NAME_EXISTS: 20404,
  DUPLICATE_RESOURCE: 20405,

  // 限制错误
  RATE_LIMIT_EXCEEDED: 20500,
  QUOTA_EXCEEDED: 20501,
  REQUEST_TOO_LARGE: 20502,

  // 文件相关错误
  FILE_NOT_FOUND: 20305,
  FILE_TYPE_NOT_ALLOWED: 20503,
  FILE_SIZE_EXCEEDED: 20504,
  FILE_UPLOAD_FAILED: 20505,
  INVALID_FILE_FORMAT: 20506,
  DUPLICATE_FILE: 20507,
  STORAGE_QUOTA_EXCEEDED: 20508,

  // 漏洞报告相关错误
  BUG_REPORT_NOT_FOUND: 20306,
  BUG_REPORT_ACCESS_DENIED: 20509,
  INVALID_BUG_SEVERITY: 20510,
  INVALID_BUG_STATUS: 20511,
  INVALID_BUG_REPORT_DATA: 20512,
  BUG_REPORT_ATTACHMENT_LIMIT_EXCEEDED: 20513,
  INVALID_ATTACHMENT_ID: 20514,
} as const

// 服务端错误状态码 (30000-39999)
const SERVER_ERROR_CODES = {
  // 通用服务端错误
  INTERNAL_SERVER_ERROR: 30000,
  SERVICE_UNAVAILABLE: 30001,
  GATEWAY_TIMEOUT: 30002,

  // 数据库相关错误
  DATABASE_ERROR: 30100,
  DATABASE_CONNECTION_ERROR: 30101,
  DATABASE_QUERY_ERROR: 30102,
  DATABASE_CONSTRAINT_ERROR: 30103,

  // 外部服务错误
  EXTERNAL_SERVICE_ERROR: 30200,
  EMAIL_SERVICE_ERROR: 30201,
  PAYMENT_SERVICE_ERROR: 30202,

  // 系统错误
  CONFIGURATION_ERROR: 30300,
  FILE_SYSTEM_ERROR: 30301,
  NETWORK_ERROR: 30302,
} as const

// 业务逻辑错误状态码 (40000-49999)
export const BUSINESS_ERROR_CODES = {
  // 用户业务错误
  CANNOT_DELETE_SELF: 40100,
  CANNOT_DISABLE_SELF: 40101,

  // 组织业务错误
  CANNOT_LEAVE_OWN_ORGANIZATION: 40201,
  CANNOT_REMOVE_ORGANIZATION_OWNER: 40202,
  ORGANIZATION_SUBSCRIPTION_REQUIRED: 40203,
  ORGANIZATION_HAS_DEPARTMENTS: 40204,
  ORGANIZATION_HAS_USERS: 40205,

  // 部门业务错误
  DEPARTMENT_HAS_CHILDREN: 40301,
  DEPARTMENT_HAS_USERS: 40302,
  DEPARTMENT_CYCLE_DETECTED: 40303,
  DEPARTMENT_MOVE_TO_DIFFERENT_ORG: 40304,

  // 接口管理业务错误
  API_TEMPORARILY_DISABLED: 40600,
  API_MAINTENANCE_MODE: 40601,

  // 漏洞报告业务错误
  CANNOT_EDIT_REVIEWED_BUG_REPORT: 40701,
  CANNOT_DELETE_REVIEWED_BUG_REPORT: 40702,
  CANNOT_APPROVE_OWN_BUG_REPORT: 40703,
  INVALID_STATUS_TRANSITION: 40704,
  BUG_REPORT_ALREADY_REVIEWED: 40705,
  CANNOT_MODIFY_CLOSED_BUG_REPORT: 40706,
} as const

// 合并所有状态码
export const BUSINESS_CODES = {
  ...SUCCESS_CODES,
  ...CLIENT_ERROR_CODES,
  ...SERVER_ERROR_CODES,
  ...BUSINESS_ERROR_CODES,
} as const

// 状态码类型
export type BusinessCode = typeof BUSINESS_CODES[keyof typeof BUSINESS_CODES]
export type BusinessErrorCode = typeof BUSINESS_ERROR_CODES[keyof typeof BUSINESS_ERROR_CODES]

// 状态码消息映射
export const BUSINESS_CODE_MESSAGES: Record<BusinessCode, string> = {
  // 成功消息
  [SUCCESS_CODES.SUCCESS]: '操作成功',
  [SUCCESS_CODES.CREATED]: '创建成功',
  [SUCCESS_CODES.UPDATED]: '更新成功',
  [SUCCESS_CODES.DELETED]: '删除成功',
  [SUCCESS_CODES.LOGIN_SUCCESS]: '登录成功',
  [SUCCESS_CODES.LOGOUT_SUCCESS]: '退出成功',
  [SUCCESS_CODES.TOKEN_REFRESHED]: '令牌刷新成功',
  [SUCCESS_CODES.PASSWORD_RESET_SUCCESS]: '密码重置成功',
  [SUCCESS_CODES.USER_CREATED]: '用户创建成功',
  [SUCCESS_CODES.USER_UPDATED]: '用户信息更新成功',
  [SUCCESS_CODES.USER_ACTIVATED]: '用户激活成功',
  [SUCCESS_CODES.USER_DEACTIVATED]: '用户禁用成功',
  [SUCCESS_CODES.ORGANIZATION_CREATED]: '组织创建成功',
  [SUCCESS_CODES.ORGANIZATION_UPDATED]: '组织信息更新成功',
  [SUCCESS_CODES.MEMBER_ADDED]: '成员添加成功',
  [SUCCESS_CODES.MEMBER_REMOVED]: '成员移除成功',

  // 漏洞报告相关成功
  [SUCCESS_CODES.BUG_REPORT_CREATED]: '漏洞报告创建成功',
  [SUCCESS_CODES.BUG_REPORT_UPDATED]: '漏洞报告更新成功',
  [SUCCESS_CODES.BUG_REPORT_SUBMITTED]: '漏洞报告提交成功',
  [SUCCESS_CODES.BUG_REPORT_APPROVED]: '漏洞报告审核通过',
  [SUCCESS_CODES.BUG_REPORT_REJECTED]: '漏洞报告已驳回',
  [SUCCESS_CODES.BUG_REPORT_RESOLVED]: '漏洞报告已解决',
  [SUCCESS_CODES.BUG_REPORT_CLOSED]: '漏洞报告已关闭',
  [SUCCESS_CODES.BUG_REPORT_STATUS_UPDATED]: '漏洞报告状态更新成功',

  // 客户端错误消息
  [CLIENT_ERROR_CODES.BAD_REQUEST]: '请求参数错误',
  [CLIENT_ERROR_CODES.VALIDATION_ERROR]: '数据验证失败',
  [CLIENT_ERROR_CODES.MISSING_PARAMETER]: '缺少必需参数',
  [CLIENT_ERROR_CODES.INVALID_PARAMETER]: '参数格式错误',
  [CLIENT_ERROR_CODES.UNAUTHORIZED]: '未经授权的访问',
  [CLIENT_ERROR_CODES.INVALID_TOKEN]: '无效的访问令牌',
  [CLIENT_ERROR_CODES.TOKEN_EXPIRED]: '访问令牌已过期',
  [CLIENT_ERROR_CODES.INVALID_CREDENTIALS]: '用户名或密码错误',
  [CLIENT_ERROR_CODES.ACCOUNT_DISABLED]: '账户已被禁用',
  [CLIENT_ERROR_CODES.FORBIDDEN]: '权限不足',
  [CLIENT_ERROR_CODES.INSUFFICIENT_PERMISSIONS]: '权限不足',
  [CLIENT_ERROR_CODES.RESOURCE_ACCESS_DENIED]: '资源访问被拒绝',
  [CLIENT_ERROR_CODES.NOT_FOUND]: '资源不存在',
  [CLIENT_ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [CLIENT_ERROR_CODES.ORGANIZATION_NOT_FOUND]: '组织不存在',
  [CLIENT_ERROR_CODES.DEPARTMENT_NOT_FOUND]: '部门不存在',
  [CLIENT_ERROR_CODES.RESOURCE_NOT_FOUND]: '请求的资源不存在',
  [CLIENT_ERROR_CODES.CONFLICT]: '资源冲突',
  [CLIENT_ERROR_CODES.EMAIL_ALREADY_EXISTS]: '邮箱已存在',
  [CLIENT_ERROR_CODES.ORGANIZATION_NAME_EXISTS]: '组织名称已存在',
  [CLIENT_ERROR_CODES.ORGANIZATION_CODE_EXISTS]: '组织编码已存在',
  [CLIENT_ERROR_CODES.DEPARTMENT_NAME_EXISTS]: '部门名称已存在',
  [CLIENT_ERROR_CODES.DUPLICATE_RESOURCE]: '资源已存在',
  [CLIENT_ERROR_CODES.RATE_LIMIT_EXCEEDED]: '请求频率超限',
  [CLIENT_ERROR_CODES.QUOTA_EXCEEDED]: '配额已超限',
  [CLIENT_ERROR_CODES.REQUEST_TOO_LARGE]: '请求体过大',
  [CLIENT_ERROR_CODES.FILE_NOT_FOUND]: '文件不存在',
  [CLIENT_ERROR_CODES.FILE_TYPE_NOT_ALLOWED]: '不支持的文件类型',
  [CLIENT_ERROR_CODES.FILE_SIZE_EXCEEDED]: '文件大小超过限制',
  [CLIENT_ERROR_CODES.FILE_UPLOAD_FAILED]: '文件上传失败',
  [CLIENT_ERROR_CODES.INVALID_FILE_FORMAT]: '文件格式无效',
  [CLIENT_ERROR_CODES.DUPLICATE_FILE]: '文件已存在',
  [CLIENT_ERROR_CODES.STORAGE_QUOTA_EXCEEDED]: '存储配额已超限',

  // 漏洞报告相关错误
  [CLIENT_ERROR_CODES.BUG_REPORT_NOT_FOUND]: '漏洞报告不存在',
  [CLIENT_ERROR_CODES.BUG_REPORT_ACCESS_DENIED]: '无权限访问该漏洞报告',
  [CLIENT_ERROR_CODES.INVALID_BUG_SEVERITY]: '无效的漏洞等级',
  [CLIENT_ERROR_CODES.INVALID_BUG_STATUS]: '无效的漏洞状态',
  [CLIENT_ERROR_CODES.INVALID_BUG_REPORT_DATA]: '漏洞报告数据无效',
  [CLIENT_ERROR_CODES.BUG_REPORT_ATTACHMENT_LIMIT_EXCEEDED]: '附件数量超出限制',
  [CLIENT_ERROR_CODES.INVALID_ATTACHMENT_ID]: '无效的附件ID',

  // 服务端错误消息
  [SERVER_ERROR_CODES.INTERNAL_SERVER_ERROR]: '服务器内部错误',
  [SERVER_ERROR_CODES.SERVICE_UNAVAILABLE]: '服务暂时不可用',
  [SERVER_ERROR_CODES.GATEWAY_TIMEOUT]: '网关超时',
  [SERVER_ERROR_CODES.DATABASE_ERROR]: '数据库错误',
  [SERVER_ERROR_CODES.DATABASE_CONNECTION_ERROR]: '数据库连接失败',
  [SERVER_ERROR_CODES.DATABASE_QUERY_ERROR]: '数据库查询错误',
  [SERVER_ERROR_CODES.DATABASE_CONSTRAINT_ERROR]: '数据库约束错误',
  [SERVER_ERROR_CODES.EXTERNAL_SERVICE_ERROR]: '外部服务错误',
  [SERVER_ERROR_CODES.EMAIL_SERVICE_ERROR]: '邮件服务错误',
  [SERVER_ERROR_CODES.PAYMENT_SERVICE_ERROR]: '支付服务错误',
  [SERVER_ERROR_CODES.CONFIGURATION_ERROR]: '配置错误',
  [SERVER_ERROR_CODES.FILE_SYSTEM_ERROR]: '文件系统错误',
  [SERVER_ERROR_CODES.NETWORK_ERROR]: '网络错误',

  // 业务错误消息
  [BUSINESS_ERROR_CODES.CANNOT_DELETE_SELF]: '不能删除自己的账户',
  [BUSINESS_ERROR_CODES.CANNOT_DISABLE_SELF]: '不能禁用自己的账户',
  [BUSINESS_ERROR_CODES.CANNOT_LEAVE_OWN_ORGANIZATION]: '不能离开自己拥有的组织',
  [BUSINESS_ERROR_CODES.CANNOT_REMOVE_ORGANIZATION_OWNER]: '不能移除组织拥有者',
  [BUSINESS_ERROR_CODES.ORGANIZATION_SUBSCRIPTION_REQUIRED]: '需要订阅组织版本',
  [BUSINESS_ERROR_CODES.ORGANIZATION_HAS_DEPARTMENTS]: '组织下存在部门，无法删除',
  [BUSINESS_ERROR_CODES.ORGANIZATION_HAS_USERS]: '组织下存在用户，无法删除',
  [BUSINESS_ERROR_CODES.DEPARTMENT_HAS_CHILDREN]: '部门下存在子部门，无法删除',
  [BUSINESS_ERROR_CODES.DEPARTMENT_HAS_USERS]: '部门下存在用户，无法删除',
  [BUSINESS_ERROR_CODES.DEPARTMENT_CYCLE_DETECTED]: '部门层级不能形成循环',
  [BUSINESS_ERROR_CODES.DEPARTMENT_MOVE_TO_DIFFERENT_ORG]: '不能将部门移动到其他组织',
  [BUSINESS_ERROR_CODES.API_TEMPORARILY_DISABLED]: '该接口已临时禁用',
  [BUSINESS_ERROR_CODES.API_MAINTENANCE_MODE]: '该接口正在维护中',

  // 漏洞报告业务错误
  [BUSINESS_ERROR_CODES.CANNOT_EDIT_REVIEWED_BUG_REPORT]: '已审核的漏洞报告无法修改',
  [BUSINESS_ERROR_CODES.CANNOT_DELETE_REVIEWED_BUG_REPORT]: '已审核的漏洞报告无法删除',
  [BUSINESS_ERROR_CODES.CANNOT_APPROVE_OWN_BUG_REPORT]: '不能审核自己提交的漏洞报告',
  [BUSINESS_ERROR_CODES.INVALID_STATUS_TRANSITION]: '无效的状态流转',
  [BUSINESS_ERROR_CODES.BUG_REPORT_ALREADY_REVIEWED]: '漏洞报告已被审核',
  [BUSINESS_ERROR_CODES.CANNOT_MODIFY_CLOSED_BUG_REPORT]: '已关闭的漏洞报告无法修改',
} as const

// 工具函数：获取状态码对应的消息
export function getBusinessCodeMessage(code: BusinessCode): string {
  return BUSINESS_CODE_MESSAGES[code] || '未知错误'
}
