# 测试环境 Docker Compose 配置
# 使用方式：docker compose -f docker-compose.test.yml up -d

services:
  # 测试环境用的 PostgreSQL 数据库
  postgres:
    image: postgres:17-alpine
    container_name: nest_postgres_test
    restart: unless-stopped
    environment:
      POSTGRES_DB: nest_api_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
      TZ: Asia/Shanghai
    ports:
      - '5434:5432' # 使用 5434 避免端口冲突
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  # Nest 应用服务 - 测试环境
  app:
    image: nest-api:test
    container_name: nest_api_test
    restart: unless-stopped
    env_file:
      - ../.env.test
    environment:
      NODE_ENV: test
      TZ: Asia/Shanghai
      # 数据库连接使用容器内网络
      DATABASE_URL: postgresql://postgres:test_password@postgres:5432/nest_api_test?schema=public
    ports:
      - '8001:8000' # 使用 8001 避免端口冲突
    depends_on:
      - postgres
    volumes:
      - app_test_storage:/app/apps/server/storage

volumes:
  postgres_test_data:
    driver: local
  app_test_storage:
    driver: local
