import type { Metadata } from 'next'

// import { Geist, Geist_Mono } from 'next/font/google'
import { ThemeProvider } from '@/components/ThemeProvider'
import { cn } from '@/lib/utils'
import { getPageTitle } from '@/utils/common'

import '@/styles/globals.css'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: getPageTitle(),
  description: 'Generated by create next app',
  icons: [{ url: '/favicon.ico', sizes: '32x32', rel: 'icon' }],
}

export default function RootLayout(props: React.PropsWithChildren) {
  return (
    <html suppressHydrationWarning className="h-full" lang="zh-CN">
      <body
        className={cn([
          'h-full antialiased',
          // `${geistSans.variable} ${geistMono.variable}`,
        ])}
      >
        <ThemeProvider
          disableTransitionOnChange
          enableSystem
          attribute="class"
          defaultTheme="system"
        >
          {props.children}
        </ThemeProvider>
      </body>
    </html>
  )
}
