services:
  web:
    platform: linux/amd64
    image: nestjs-docs-web:latest
    ports:
      - '3001:8080' # 宿主机:容器内部
    env_file:
      - ../.env.test # 使用测试环境配置
    environment:
      # 覆盖测试环境中需要容器化调整的配置
      - NODE_ENV=test
    restart: unless-stopped
    # 如果后端也在 Docker 中运行，可以添加网络配置
    # networks:
    #   - app-network
# 如果需要与其他服务（如数据库、后端API）连接，可以取消注释以下配置
# networks:
#   app-network:
#     driver: bridge
