services:
  web:
    platform: linux/amd64
    image: nestjs-docs-web:latest
    ports:
      - '3001:8080' # 宿主机:容器内部
    # 环境变量已硬编码到 Dockerfile 中，不再需要外部文件
    # env_file:
    #   - ../.env.test
    # environment:
    #   # 以下环境变量已在 Dockerfile 中硬编码：
    #   # NODE_ENV=test
    #   # NEXT_PUBLIC_ORAMA_API_KEY=UPc31JnTgKtFPL3bUzL18XfZ8zyiiz0G
    #   # NEXT_PUBLIC_ORAMA_ENDPOINT=https://cloud.orama.run/v1/indexes/nestjs-docs-leoku-dev-j21flz
    #   # NEXT_PUBLIC_ENABLE_PAID_CONTENT_MODE=false
    #   # NEXT_PUBLIC_API_BASE=https://172.168.88.192:8084
    #   # NEXT_PUBLIC_API_PROXY_SOURCE=/api
    #   # NEXT_PUBLIC_API_PROXY_DESTINATION=https://172.168.88.192:8084/api
    #   # NEXT_PUBLIC_JWT_USE_COOKIE=false
    #   # NEXT_PUBLIC_PROJECT_FLAG=crowd-test
    restart: unless-stopped
    # 如果后端也在 Docker 中运行，可以添加网络配置
    # networks:
    #   - app-network
# 如果需要与其他服务（如数据库、后端API）连接，可以取消注释以下配置
# networks:
#   app-network:
#     driver: bridge
